#Programa de Teste Python (Pitão ou Piton)

print("WADAJU SOFTWARE SOLUTIONS")
print("Teste de entrada e saída")
nome = input("Qual o seu nome? ")
idade = input("Qual a sua idade? ")
peso = input("Qual o seu peso(massa)? ")
print('Olá',nome,'!')
print('Seu peso é',peso,'kg')
print('Sua idade é',idade,'anos')
